In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [9]:
dataset = pd.read_excel('dataset.xlsx')
dataset.head()

Jenis Kelamin  Umur Karyawan      Gaji   Status       Transportasi
0     Laki-Laki             20   8000000   Single  Kendaraan pribadi
1     Laki-Laki             35  14000000   Single     Kendaraan umum
2     Perempuan             26  10000000   Single     Kendaraan umum
3     Perempuan             27  12000000  Menikah  Kendaraan pribadi
4     Laki-Laki             21   9000000   Single  Kendaraan pribadi

In [10]:
dataset

Jenis Kelamin  Umur Karyawan      Gaji   Status       Transportasi
0     Laki-Laki             20   8000000   Single  Kendaraan pribadi
1     Laki-Laki             35  14000000   Single     Kendaraan umum
2     Perempuan             26  10000000   Single     Kendaraan umum
3     Perempuan             27  12000000  Menikah  Kendaraan pribadi
4     Laki-Laki             21   9000000   Single  Kendaraan pribadi
5     Laki-Laki             22  11000000   Single  Kendaraan pribadi
6     Perempuan             32  15000000  Menikah     Kendaraan umum
7     Perempuan             26   8000000  Menikah     Kendaraan umum
8     Laki-Laki             25   9000000   Single     Kendaraan umum
9     Perempuan             20  10000000   Single  Kendaraan pribadi

In [16]:
x = dataset.iloc[:, :4].values
y = dataset.iloc[:, 4].values

In [17]:
print(x)

[['Laki-Laki' 20 8000000 'Single']
 ['Laki-Laki' 35 14000000 'Single']
 ['Perempuan' 26 10000000 'Single']
 ['Perempuan' 27 12000000 'Menikah']
 ['Laki-Laki' 21 9000000 'Single']
 ['Laki-Laki' 22 11000000 'Single']
 ['Perempuan' 32 15000000 'Menikah']
 ['Perempuan' 26 8000000 'Menikah']
 ['Laki-Laki' 25 9000000 'Single']
 ['Perempuan' 20 10000000 'Single']]


In [18]:
print(y)

['Kendaraan pribadi' 'Kendaraan umum' 'Kendaraan umum' 'Kendaraan pribadi'
 'Kendaraan pribadi' 'Kendaraan pribadi' 'Kendaraan umum' 'Kendaraan umum'
 'Kendaraan umum' 'Kendaraan pribadi']


In [21]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()

x[:,0] = le.fit_transform(x[:,0])
x[:,3] = le.fit_transform(x[:,3])

In [25]:
print(x)

[[0 20 8000000 1]
 [0 35 14000000 1]
 [1 26 10000000 1]
 [1 27 12000000 0]
 [0 21 9000000 1]
 [0 22 11000000 1]
 [1 32 15000000 0]
 [1 26 8000000 0]
 [0 25 9000000 1]
 [1 20 10000000 1]]


In [27]:
y = le.fit_transform(y)
print(y)

[0 1 1 0 0 0 1 1 1 0]


In [28]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [31]:
print(x_train)

[[0 21 9000000 1]
 [1 20 10000000 1]
 [0 35 14000000 1]
 [1 32 15000000 0]
 [1 26 8000000 0]
 [1 27 12000000 0]
 [0 20 8000000 1]
 [0 22 11000000 1]]


In [32]:
print(x_test)

[[1 26 10000000 1]
 [0 25 9000000 1]]


In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [35]:
print(x_train)

[[-1.         -0.81973732 -0.75858261  0.77459667]
 [ 1.         -1.00710586 -0.35400522  0.77459667]
 [-1.          1.80342211  1.26430434  0.77459667]
 [ 1.          1.24131652  1.66888173 -1.29099445]
 [ 1.          0.11710533 -1.16316    -1.29099445]
 [ 1.          0.30447386  0.45514956 -1.29099445]
 [-1.         -1.00710586 -1.16316     0.77459667]
 [-1.         -0.63236879  0.05057217  0.77459667]]


In [36]:
from sklearn.naive_bayes import GaussianNB

In [37]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [38]:
y_pred = classifier.predict(x_test)

In [39]:
print(y_pred)

[1 0]


In [40]:
print(y_test)

[1 1]


In [41]:
datatest = pd.read_excel('datatest.xlsx')
datatest

Jenis Kelamin  Umur Karyawan      Gaji   Status
0     Perempuan             27  12000000   Single
1     Laki-Laki             35  14000000  Menikah

In [44]:
z = datatest.iloc[:, :4].values
print(z)

[['Perempuan' 27 12000000 'Single']
 ['Laki-Laki' 35 14000000 'Menikah']]


In [45]:
z[:,0] = le.fit_transform(z[:,0])
z[:,3] = le.fit_transform(z[:,3])
print(z)

[[1 27 12000000 1]
 [0 35 14000000 0]]


In [48]:
z_pred = classifier.predict(z)
print(z_pred)

[1 1]
